---

modules:
  mbr:
  - entry
  - disk
  - io
  - partition_table
  stage2:
  - entry
  - gdt
  - pmode
  - video
  - a20
  - mem
  - debug
  - diskio
  - fat

debug: true

stage2:
  # stage 2 base address.
  # this is where stage2 will be loaded
  smap:
    base: 0x7000
    length: 0xB00
  # stage 2 location on disk
  disk:
    c: 0
    h: 0
    s: 2
  fat:
    feature:
      read: true
      dir: false
      lseek: false
      write: false
    filesystem:
      fat12: false
      fat16: true
      fat32: false
    namespace:
      lowercase_paths: false
      codepage: 437
    system:
      word_access: false
