---

modules:
  mbr:
  - entry
  - disk
  - io
  - partition_table
  stage2:
  - entry
  - gdt
  - pmode
  - video
  - a20
  - mem
  - debug

debug: true

stage1:
  stack_top: 0x7C00
  load_address: 0x7C00

stage2:
  load_address: 0x8000
  # stage 2 base address.
  # this is where stage2 will be loaded
  smap:
    base: 0x7000
    length: 0xB00
  # stage 2 location on disk
  disk:
    c: 0
    h: 0
    s: 2

partition:
  1:
    set: true
    status: "ACTIVE"
    start: (0,0,1)
    end: (1023,254,23)
    type: 0x0B #FAT32
    first_sector: 63
    num_sectors: 131009
  2:
    set: false
  3:
    set: false
  4:
    set: false
